version: "3.9"
name: tiros
services:
  ipfs:
    image: helia-http-gateway:latest
    restart: unless-stopped
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    environment:
      DEBUG: helia-server
    ports:
      - "0.0.0.0:${HELIA_PORT:-8080}:8080"
  chrome:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
  db:
    image: postgres:14
    ports:
      - "0.0.0.0:${TIROS_RUN_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tiros_test
      POSTGRES_DB: tiros_test
volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse: